parameters:
    emoji.emoji.class: 'Jadu\Emoji\Emoji'
    emoji.emoji.index.class: 'Jadu\Emoji\Index\CompiledIndex'
    emoji.twig.extension.class: 'Jadu\EmojiBundle\Twig\Extension\EmojiExtension'

services:
    emoji:
        class: '%emoji.emoji.class%'
        arguments:
            - '@emoji.index'
            - '%emoji.image_html_template%'

    emoji.index:
        class: '%emoji.emoji.index.class%'

    emoji.twig.extension:
        class: '%emoji.twig.extension.class%'
        arguments:
            - '@emoji'
        public: false
        tags:
            - { name: twig.extension }
